### ISSUE TITLE
Hit decal on doors

### ISSUE THREAD

**Issue by ghost** [Reperio-Studios/BrainBread-2-Issues#1]
Hello,

The bug is when you hit a door, the hit decal shows repeated.
![2015-03-14_00002](https://cloud.githubusercontent.com/assets/1896694/6653520/d748f0ce-ca8d-11e4-8bb5-6334a6c8be8c.jpg)

**Comment by jonnyboy0719** [comment]
We won't be using the HL2 prop doors later on, since ours will be destructible.
