### ISSUE TITLE
Mac OS X - Creating Lan server

### ISSUE THREAD

**Issue by ghost** [Reperio-Studios/BrainBread-2-Issues#4]
I have tested the Steam build ID for 632894 and it turns out that when getting onto the lan  server it don't show up anything and I can't move at all. 

Problem is shown below:

![screen shot 2015-05-26 at 14 42 03](https://cloud.githubusercontent.com/assets/1896694/7813816/e91da00e-03b5-11e5-89e9-2a2d84916c5e.png)

This is after i verify game content below: 
![screen shot 2015-05-26 at 14 53 26](https://cloud.githubusercontent.com/assets/1896694/7813988/09ec8fe2-03b7-11e5-81de-0101bad370c3.png)

**Comment by BerntA** [comment]
This bug happened before when you joined a server with profile saving, it basically wouldn't spawn you, try to disable bb2_allow_profile_system then test again and try to add in sv_lan 1 too, remember that the MAC build is veeery outdated. Also if you verify cache it will give you the shared content for the current version and it may remove old content too so things may break even more that way. hehe.
